# OpenWebUI Configuration Sample for AWS Bedrock Agent
# This file shows how to configure OpenWebUI to work with your Bedrock Agent

# AWS Configuration
aws:
  region: "us-east-1"  # Change to your preferred region
  profile: "default"   # AWS CLI profile to use

# Bedrock Agent Configuration
bedrock:
  agent_id: ""        # Will be populated from CloudFormation outputs
  agent_alias_id: ""  # Will be populated from CloudFormation outputs
  model_id: "anthropic.claude-3-5-sonnet-20241022-v2:0"

# OpenWebUI Settings
openwebui:
  # API Configuration
  api_base_url: "http://localhost:8080"  # OpenWebUI instance URL

  # Model Settings
  model_name: "Bedrock-Agent-Claude-Sonnet"
  model_display_name: "Claude Sonnet 3.7 (Bedrock Agent)"

  # Chat Settings
  max_tokens: 4096
  temperature: 0.7
  top_p: 0.9
  top_k: 250

  # Agent Settings
  enable_agent_mode: true
  agent_session_timeout: 3600  # 1 hour

  # Streaming
  enable_streaming: true

# Test Configuration
test:
  session_id: "openwebui-test-session"
  sample_prompts:
    - "Hello! Can you introduce yourself?"
    - "What are your capabilities?"
    - "Can you help me with a coding question?"
    - "Tell me about AWS Bedrock Agents"

# Monitoring
monitoring:
  enable_logging: true
  log_level: "INFO"
  cloudwatch_log_group: "/aws/bedrock/TestAgent-dev"  # Will match CloudFormation output

# Environment Variables (for OpenWebUI deployment)
environment_variables:
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "default"
  BEDROCK_AGENT_ID: ""      # From CloudFormation output
  BEDROCK_AGENT_ALIAS_ID: "" # From CloudFormation output
  OPENWEBUI_API_BASE_URL: "http://localhost:8080"
  OPENWEBUI_MODEL_NAME: "Bedrock-Agent-Claude-Sonnet"
